import type { PiAgentKind } from '../../shared/pi-agent-kind'

export function getPiAgentStatusPostQueueSourceLines(kind: PiAgentKind): string[] {
  return [
    'type HookPost = { hookEventName: string; extra: Record<string, unknown>; metadata: Record<string, unknown>; ompRuntime: boolean; revision: number; attempts: number; delivered: boolean; final?: boolean }',
    'type HookPostQueue = { activePost: HookPost | null; pendingPost: HookPost | null; latestPost: HookPost | null; finalPosts: HookPost[]; finalRetryTimer: ReturnType<typeof setTimeout> | null; postRevision: number; retryTimer: ReturnType<typeof setTimeout> | null }',
    ...(kind === 'pi'
      ? [
          'declare global { var __orcaPiStatusPostQueue: HookPostQueue | undefined }',
          // Why: old delivery continuations and a reloaded registration must serialize through one queue.
          'const postQueue: HookPostQueue = globalThis.__orcaPiStatusPostQueue ??= { activePost: null, pendingPost: null, latestPost: null, finalPosts: [], finalRetryTimer: null, postRevision: 0, retryTimer: null }'
        ]
      : [
          'const postQueue: HookPostQueue = { activePost: null, pendingPost: null, latestPost: null, finalPosts: [], finalRetryTimer: null, postRevision: 0, retryTimer: null }'
        ]),
    '',
    'function cancelPostRetry(): void {',
    '  if (postQueue.retryTimer !== null) clearTimeout(postQueue.retryTimer)',
    '  postQueue.retryTimer = null',
    '}',
    '',
    '// Why: a queued or scheduled post builds its body later, so it already carries newer state.',
    'function hasQueuedPost(): boolean {',
    '  return postQueue.pendingPost !== null || postQueue.retryTimer !== null',
    '}',
    '',
    'function resetPostQueue(): void {',
    '  cancelPostRetry()',
    '  postQueue.postRevision++',
    // Why: preserve the original object so an in-flight acknowledgment also retires its final queue entry.
    '  for (const post of [postQueue.activePost, postQueue.pendingPost, postQueue.latestPost]) {',
    "    if (!post || post.hookEventName !== 'agent_end' || post.delivered || post.final) continue",
    '    post.final = true',
    '    postQueue.finalPosts.push(post)',
    '  }',
    '  postQueue.pendingPost = null',
    '  postQueue.latestPost = null',
    '  drainPosts()',
    '}',
    '',
    'function retireTurnCompletionPosts(metadata: Record<string, unknown>): void {',
    '  const first = postQueue.finalPosts[0]',
    '  for (const post of postQueue.finalPosts) {',
    '    if (post.extra.session_boundary !== true && post.metadata.session_id === metadata.session_id) post.final = false',
    '  }',
    '  postQueue.finalPosts = postQueue.finalPosts.filter((post) => post.final)',
    '  if (first && !first.final && postQueue.finalRetryTimer !== null) {',
    '    clearTimeout(postQueue.finalRetryTimer)',
    '    postQueue.finalRetryTimer = null',
    '  }',
    '}',
    '',
    'function drainPosts(): void {',
    // Why: a final post waiting to retry holds newer posts back, so the old session's row is never written last.
    '  if (postQueue.activePost || postQueue.finalRetryTimer !== null) return',
    '  const next = postQueue.finalPosts[0] ?? postQueue.pendingPost',
    '  if (!next) return',
    '  if (!next.final) postQueue.pendingPost = null',
    '  postQueue.activePost = next',
    '  void postOnce(next.hookEventName, next.extra, next.metadata, next.ompRuntime, next.final === true)',
    '    .then(() => {',
    '      next.delivered = true',
    '      if (next.final) postQueue.finalPosts.shift()',
    '    })',
    '    .catch(() => {',
    '      if (next.final) {',
    '        if (next.attempts >= 3) {',
    '          postQueue.finalPosts.shift()',
    "          console.warn('[orca-pi-status] hook delivery failed after retries:', next.hookEventName)",
    '          return',
    '        }',
    '        postQueue.finalRetryTimer = setTimeout(() => {',
    '          postQueue.finalRetryTimer = null',
    '          drainPosts()',
    '        }, 250 * 2 ** next.attempts++)',
    "        if (typeof postQueue.finalRetryTimer.unref === 'function') postQueue.finalRetryTimer.unref()",
    '        return',
    '      }',
    '      if (!next.ompRuntime || next.revision !== postQueue.postRevision) return',
    '      if (next.attempts >= 3) {',
    "        console.warn('[orca-pi-status] hook delivery failed after retries:', next.hookEventName)",
    '        return',
    '      }',
    '      const delay = 250 * 2 ** next.attempts++',
    '      postQueue.retryTimer = setTimeout(() => {',
    '        postQueue.retryTimer = null',
    '        if (next.revision !== postQueue.postRevision) return',
    '        postQueue.pendingPost = next',
    '        drainPosts()',
    '      }, delay)',
    "      if (typeof postQueue.retryTimer.unref === 'function') postQueue.retryTimer.unref()",
    '    })',
    '    .finally(() => {',
    '      postQueue.activePost = null',
    '      drainPosts()',
    '    })',
    '}',
    ''
  ]
}
