export const WORKTREE_LINKED_ITEMS_RUNTIME_CAPABILITY = 'worktree.linked-items.v1'
export const WORKTREE_LINKED_ITEMS_DELTA_RUNTIME_CAPABILITY = 'worktree.linked-items-delta.v1'

export const WORKSPACE_ATTACHMENT_RUNTIME_CAPABILITIES = [
  WORKTREE_LINKED_ITEMS_RUNTIME_CAPABILITY,
  WORKTREE_LINKED_ITEMS_DELTA_RUNTIME_CAPABILITY
] as const
