import { existsSync } from 'node:fs'
import { mkdir, mkdtemp, rm, symlink, writeFile } from 'node:fs/promises'
import { tmpdir } from 'node:os'
import { join } from 'node:path'
import { afterEach, beforeEach, describe, expect, it } from 'vitest'
import type { Repo } from '../shared/repo-types'
import {
  collectWorktreeTrashSweepRoots,
  sweepStaleWorktreeTrash,
  WORKTREE_TRASH_DIR_NAME
} from './worktree-trash'

let scratchDir = ''

beforeEach(async () => {
  scratchDir = await mkdtemp(join(tmpdir(), 'orca-worktree-trash-'))
})

afterEach(async () => {
  await rm(scratchDir, { recursive: true, force: true })
})

async function createWorktreeDirectory(worktreePath: string): Promise<void> {
  await mkdir(join(worktreePath, 'node_modules', 'pkg'), { recursive: true })
  await writeFile(join(worktreePath, 'node_modules', 'pkg', 'index.js'), 'module.exports = 1\n')
}

describe('sweepStaleWorktreeTrash', () => {
  it('removes leftover entries from both workspace layouts and nothing else', async () => {
    const nestedTrashRoot = join(scratchDir, 'repo', WORKTREE_TRASH_DIR_NAME)
    const flatTrashRoot = join(scratchDir, WORKTREE_TRASH_DIR_NAME)
    await mkdir(join(nestedTrashRoot, 'wt-1700000000000-abcdef01', 'src'), { recursive: true })
    await mkdir(join(flatTrashRoot, 'wt-1700000000001-abcdef02'), { recursive: true })
    // Not generated by Orca: a stray directory and file inside the trash root must survive.
    await mkdir(join(nestedTrashRoot, 'unrelated-directory'), { recursive: true })
    await writeFile(join(nestedTrashRoot, 'wt-notes.txt'), 'keep me\n')
    const liveWorktree = join(scratchDir, 'repo', 'feature')
    await createWorktreeDirectory(liveWorktree)

    const { removed } = await sweepStaleWorktreeTrash([scratchDir])

    expect(removed).toBe(2)
    expect(existsSync(join(nestedTrashRoot, 'wt-1700000000000-abcdef01'))).toBe(false)
    expect(existsSync(join(flatTrashRoot, 'wt-1700000000001-abcdef02'))).toBe(false)
    expect(existsSync(join(nestedTrashRoot, 'unrelated-directory'))).toBe(true)
    expect(existsSync(join(nestedTrashRoot, 'wt-notes.txt'))).toBe(true)
    expect(existsSync(join(liveWorktree, 'node_modules', 'pkg', 'index.js'))).toBe(true)
    // Nothing refills a trash root, so an emptied one goes; one still holding foreign entries stays.
    expect(existsSync(flatTrashRoot)).toBe(false)
    expect(existsSync(nestedTrashRoot)).toBe(true)
  })

  it('ignores workspace roots that do not exist', async () => {
    expect(await sweepStaleWorktreeTrash([join(scratchDir, 'missing')])).toEqual({ removed: 0 })
  })

  it('never descends past the trash roots beside worktrees', async () => {
    const deepTrashRoot = join(scratchDir, 'repo', 'feature', WORKTREE_TRASH_DIR_NAME)
    await mkdir(join(deepTrashRoot, 'wt-1700000000002-abcdef03'), { recursive: true })

    expect(await sweepStaleWorktreeTrash([scratchDir])).toEqual({ removed: 0 })
    expect(existsSync(join(deepTrashRoot, 'wt-1700000000002-abcdef03'))).toBe(true)
  })

  it.skipIf(process.platform === 'win32')(
    'does not sweep through a symlinked trash root',
    async () => {
      const externalEntry = join(scratchDir, 'external', 'wt-1700000000003-abcdef04')
      await mkdir(externalEntry, { recursive: true })
      await symlink(join(scratchDir, 'external'), join(scratchDir, WORKTREE_TRASH_DIR_NAME))

      expect(await sweepStaleWorktreeTrash([scratchDir])).toEqual({ removed: 0 })
      expect(existsSync(externalEntry)).toBe(true)
    }
  )
})

describe('collectWorktreeTrashSweepRoots', () => {
  const settings = { workspaceDir: '/home/dev/orca/workspaces', nestWorkspaces: true }

  function repo(overrides: Partial<Repo>): Repo {
    return { id: 'repo-1', path: '/home/dev/code/orca', ...overrides } as unknown as Repo
  }

  it('collects one root per local git repo', () => {
    expect(
      collectWorktreeTrashSweepRoots(
        [repo({}), repo({ id: 'repo-2', path: '/code/other' })],
        settings
      )
    ).toEqual(['/home/dev/orca/workspaces'])
  })

  it('honours a repo-specific worktree base path', () => {
    expect(
      collectWorktreeTrashSweepRoots([repo({ worktreeBasePath: '/volumes/fast/trees' })], settings)
    ).toEqual(['/volumes/fast/trees'])
  })

  it('skips SSH repos and folder workspaces', () => {
    expect(
      collectWorktreeTrashSweepRoots(
        [repo({ connectionId: 'ssh-1' }), repo({ id: 'repo-3', kind: 'folder' })],
        settings
      )
    ).toEqual([])
  })

  it('skips WSL repos that cannot create host trash', () => {
    const originalPlatform = process.platform
    Object.defineProperty(process, 'platform', { configurable: true, value: 'win32' })
    try {
      expect(
        collectWorktreeTrashSweepRoots(
          [
            repo({ path: '\\\\wsl.localhost\\Ubuntu\\home\\dev\\orca' }),
            repo({
              id: 'repo-2',
              path: 'C:\\code\\orca',
              worktreeBasePath: '\\\\wsl.localhost\\Ubuntu\\home\\dev\\trees'
            })
          ],
          settings
        )
      ).toEqual([])
    } finally {
      Object.defineProperty(process, 'platform', { configurable: true, value: originalPlatform })
    }
  })
})
