import { useCallback, useEffect, type Dispatch, type RefObject, type SetStateAction } from 'react'
import { getConnectionId } from '@/lib/connection-context'
import { useAppStore, type AppState } from '@/store'
import {
  cancelRuntimeGeneratePullRequestFields,
  generateRuntimePullRequestFields,
  type RuntimeGeneratePullRequestFieldsOverrides
} from '@/runtime/runtime-git-client'
import type { HostedReviewCreationEligibility } from '../../../../shared/hosted-review'
import type { ResolveSourceControlAiResult } from '../../../../shared/source-control-ai'
import type { SourceControlAiPrCreationDefaults } from '../../../../shared/source-control-ai-types'
import type { PullRequestFieldRevisions } from '@/store/slices/pull-request-generation'
import type { PullRequestGenerationOptions } from '@/store/slices/pull-request-generation-auto-submit'
import { stripBaseRef } from './create-pull-request-base-ref-normalization'
import type {
  GenerationSeed,
  PullRequestGenerationOutcome,
  PullRequestDraftFields,
  UseCreatePullRequestDialogFieldsOptions
} from './create-pull-request-dialog-field-model'

type CreatePullRequestFieldGenerationOptions = {
  open: boolean
  submitting: boolean
  resolvedPullRequestAi: ResolveSourceControlAiResult | null
  base: string
  title: string
  body: string
  draft: boolean
  worktreeId: string | null
  worktreePath: string
  settings: AppState['settings']
  eligibility: HostedReviewCreationEligibility | null
  resolvedPrDefaults: Required<SourceControlAiPrCreationDefaults>
  generation: UseCreatePullRequestDialogFieldsOptions['generation']
  onBranchChangedByGeneration?: () => Promise<void>
  applyGeneratedFields: (
    fields: PullRequestDraftFields,
    seedRevisions: PullRequestFieldRevisions
  ) => PullRequestDraftFields
  generating: boolean
  generateError: string | null
  setGenerating: Dispatch<SetStateAction<boolean>>
  setGenerateError: Dispatch<SetStateAction<string | null>>
  initializedFromEligibilityRef: RefObject<string | null>
  autoGeneratedForKeyRef: RefObject<string | null>
  generateInFlightRef: RefObject<boolean>
  generationRequestIdRef: RefObject<number>
  generationSeedRef: RefObject<GenerationSeed | null>
  fieldRevisionsRef: RefObject<PullRequestFieldRevisions>
}

type CreatePullRequestFieldGenerationResult = {
  effectiveGenerating: boolean
  effectiveGenerateError: string | null
  generateDisabled: boolean
  generateDisabledReason: string | undefined
  handleGenerate: (
    overrides?: RuntimeGeneratePullRequestFieldsOverrides,
    options?: PullRequestGenerationOptions
  ) => Promise<PullRequestGenerationOutcome | void>
  handleCancelGenerate: () => void
}

export function useCreatePullRequestFieldGeneration({
  open,
  submitting,
  resolvedPullRequestAi,
  base,
  title,
  body,
  draft,
  worktreeId,
  worktreePath,
  settings,
  eligibility,
  resolvedPrDefaults,
  generation,
  onBranchChangedByGeneration,
  applyGeneratedFields,
  generating,
  generateError,
  setGenerating,
  setGenerateError,
  initializedFromEligibilityRef,
  autoGeneratedForKeyRef,
  generateInFlightRef,
  generationRequestIdRef,
  generationSeedRef,
  fieldRevisionsRef
}: CreatePullRequestFieldGenerationOptions): CreatePullRequestFieldGenerationResult {
  const effectiveGenerating = generation?.generating ?? generating
  const effectiveGenerateError = generation?.generateError ?? generateError

  let generateDisabledReason: string | undefined
  if (submitting) {
    generateDisabledReason = 'Create PR in progress...'
  } else if (!resolvedPullRequestAi?.ok) {
    generateDisabledReason =
      resolvedPullRequestAi?.error ?? 'Enable Source Control AI in Settings -> Git.'
  } else if (!base.trim()) {
    generateDisabledReason = 'Choose a base branch before generating.'
  }
  const generateDisabled = !effectiveGenerating && Boolean(generateDisabledReason)

  const handleGenerate = useCallback(
    async (
      overrides?: RuntimeGeneratePullRequestFieldsOverrides,
      options?: PullRequestGenerationOptions
    ): Promise<PullRequestGenerationOutcome | void> => {
      if (!worktreePath || !base.trim() || effectiveGenerating || generateDisabled) {
        return
      }
      if (generation) {
        return await generation.onGenerate(
          { base, title, body, draft },
          { ...fieldRevisionsRef.current },
          overrides,
          options
        )
      }
      const requestId = generationRequestIdRef.current + 1
      generationRequestIdRef.current = requestId
      const connectionId = getConnectionId(worktreeId) ?? undefined
      const requestContext = {
        // Why: PR generation belongs to the visible worktree owner. Global
        // focused-host changes must not retarget an in-flight generation.
        settings,
        worktreeId,
        worktreePath,
        connectionId
      }
      const seed = {
        requestId,
        fieldRevisions: { ...fieldRevisionsRef.current },
        context: requestContext
      }
      generationSeedRef.current = seed
      generateInFlightRef.current = true
      setGenerating(true)
      setGenerateError(null)
      try {
        const result = await generateRuntimePullRequestFields(
          requestContext,
          {
            base: stripBaseRef(base.trim()),
            title,
            body,
            draft,
            provider: eligibility?.provider,
            useTemplate: resolvedPrDefaults.useTemplate
          },
          overrides
        )
        if (result.branchChangedByPreparation) {
          await onBranchChangedByGeneration?.()
        }
        const isCurrentRequest = generationRequestIdRef.current === requestId
        if (!isCurrentRequest) {
          return { result: null }
        }
        if (!result.success) {
          if (result.canceled) {
            setGenerateError(null)
            return { result: null }
          }
          setGenerateError(result.error)
          return { result: null }
        }

        const currentSeed = generationSeedRef.current
        if (!currentSeed || currentSeed.requestId !== requestId) {
          return { result: null }
        }
        const shownFields = applyGeneratedFields(result.fields, currentSeed.fieldRevisions)
        useAppStore.getState().recordFeatureInteraction('ai-pr-generation')
        setGenerateError(null)
        return { result: shownFields }
      } catch (error) {
        if (generationRequestIdRef.current !== requestId) {
          return { result: null }
        }
        setGenerateError(
          error instanceof Error ? error.message : 'Failed to generate pull request details'
        )
        return { result: null }
      } finally {
        if (generationRequestIdRef.current === requestId) {
          generateInFlightRef.current = false
          generationSeedRef.current = null
          setGenerating(false)
        }
      }
    },
    [
      base,
      body,
      draft,
      effectiveGenerating,
      applyGeneratedFields,
      eligibility?.provider,
      fieldRevisionsRef,
      generateInFlightRef,
      generation,
      generateDisabled,
      generationRequestIdRef,
      generationSeedRef,
      onBranchChangedByGeneration,
      resolvedPrDefaults.useTemplate,
      setGenerateError,
      setGenerating,
      settings,
      title,
      worktreeId,
      worktreePath
    ]
  )

  const handleCancelGenerate = useCallback((): void => {
    if (generation) {
      generation.onCancelGenerate()
      return
    }
    const requestContext = generationSeedRef.current?.context
    if (!requestContext?.worktreePath || !generateInFlightRef.current) {
      return
    }
    generationRequestIdRef.current += 1
    generateInFlightRef.current = false
    generationSeedRef.current = null
    setGenerating(false)
    setGenerateError(null)
    void cancelRuntimeGeneratePullRequestFields(requestContext)
  }, [
    generateInFlightRef,
    generation,
    generationRequestIdRef,
    generationSeedRef,
    setGenerateError,
    setGenerating
  ])

  useEffect(() => {
    if (
      !open ||
      !resolvedPrDefaults.generateDetailsOnOpen ||
      !initializedFromEligibilityRef.current ||
      autoGeneratedForKeyRef.current === initializedFromEligibilityRef.current ||
      generateDisabled ||
      effectiveGenerating ||
      !base.trim()
    ) {
      return
    }
    autoGeneratedForKeyRef.current = initializedFromEligibilityRef.current
    void handleGenerate()
  }, [
    autoGeneratedForKeyRef,
    base,
    effectiveGenerating,
    generateDisabled,
    handleGenerate,
    initializedFromEligibilityRef,
    open,
    resolvedPrDefaults.generateDetailsOnOpen
  ])

  return {
    effectiveGenerating,
    effectiveGenerateError,
    generateDisabled,
    generateDisabledReason,
    handleGenerate,
    handleCancelGenerate
  }
}
